DefaultContentLanguage = "en"
author = "Jorden Senior"
baseURL = "https://jordensenior.com"
copyright = "Copyright © 2025"
disqusShortname = "JordeSenior"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
googleAnalytics = "UA-FAKE" ## or "G-xxxxxxxx" in Google Analytics v4, in hugo v0.82+
hasCJKLanguage = true
languageCode = "en"
theme = "tokiwa"
title = "Jorden Senior"

[markup]
[markup.highlight]
style = "monokailight"

[markup.goldmark.renderer]
unsafe = true

[params]

bannerFont = "fonts/exampleFont" 
description = """
Tokiwa-iro is the theme color of this site.
""" 
env = "production" # for Google Analytics and DISQUS.
favicon = "img/favicon-32x32.png" 
fuse = true # for searchbox. "JSON" must added to output contents. See [outputs].
math = true # for introducing $KaTeX$
useChineseFonts = true 
postDateFormat = "2006-1-2"
customCSS = ["css/custom.css"]
[menu]
# Shown in the side menu.
[[menu.main]]
identifier = "Experiment"
name = "Experiments"
url = "/experiments/"
weight = 1
#[[menu.main]]
#name = "Tags"
#url = "/tags/"
#weight = 2

#[[menu.main]]
#name = "Categories"
#url = "/categories/"
#weight = 2

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 3

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
[params.social]
github = "https://github.com/jordensenior"
instagram = "http://instagram.com/jordensenior"
mail = "mailto:contact@jordensenior.com"
# any icon in layouts/partials/svg can be used by the name without the "-line.svg"

[outputs]
home = ["HTML",  "JSON"]